export default {
  SET_USER: 'SET_USER',
  SET_LOGOUT: 'SET_LOGOUT',
  SET_AUTH_USER: 'SET_AUTH_USER',
  UPDATE_USER: 'UPDATE_USER',
  ADD_USER_FOLDER: 'ADD_USER_FOLDER',
  REMOVE_USER_FOLDER: 'REMOVE_USER_FOLDER'
}
