export default {
  SET_USER: 'SET_USER',
  SET_LOGOUT: 'SET_LOGOUT',
  SET_AUTH_USER: 'SET_AUTH_USER',
  SET_USER_FOLDERS: 'SET_USER_FOLDERS',
  SET_USER_FOLDER: 'SET_USER_FOLDER',
  REMOVE_PROJECT_FROM_USER_FOLDER: 'REMOVE_PROJECT_FROM_USER_FOLDER',
  UPDATE_USER: 'UPDATE_USER'
}
